[package]
name = "libengine"
version = "0.1.0"
edition = "2021"

[lib]
name = "native_bench_api"
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.22"
libloading = "0.7"
nix = "0.26.2"
libc="0.2"